// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package contracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for QuickAddParsedType.
const (
	QuickAddParsedTypeExpense QuickAddParsedType = "expense"
	QuickAddParsedTypeIncome  QuickAddParsedType = "income"
)

// Valid indicates whether the value is a known member of the QuickAddParsedType enum.
func (e QuickAddParsedType) Valid() bool {
	switch e {
	case QuickAddParsedTypeExpense:
		return true
	case QuickAddParsedTypeIncome:
		return true
	default:
		return false
	}
}

// Defines values for TransactionType.
const (
	TransactionTypeExpense TransactionType = "expense"
	TransactionTypeIncome  TransactionType = "income"
)

// Valid indicates whether the value is a known member of the TransactionType enum.
func (e TransactionType) Valid() bool {
	switch e {
	case TransactionTypeExpense:
		return true
	case TransactionTypeIncome:
		return true
	default:
		return false
	}
}

// Defines values for TransactionCreateType.
const (
	Expense TransactionCreateType = "expense"
	Income  TransactionCreateType = "income"
)

// Valid indicates whether the value is a known member of the TransactionCreateType enum.
func (e TransactionCreateType) Valid() bool {
	switch e {
	case Expense:
		return true
	case Income:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string    `json:"code"`
	Details *[]string `json:"details,omitempty"`
	Message string    `json:"message"`
}

// FamilyGroup defines model for FamilyGroup.
type FamilyGroup struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	CreatedBy *openapi_types.UUID `json:"created_by,omitempty"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
}

// FamilyGroupCreate defines model for FamilyGroupCreate.
type FamilyGroupCreate struct {
	Name string `json:"name"`
}

// MonthlyReport defines model for MonthlyReport.
type MonthlyReport struct {
	Balance      float32             `json:"balance"`
	Categories   *map[string]float32 `json:"categories,omitempty"`
	TotalExpense float32             `json:"total_expense"`
	TotalIncome  float32             `json:"total_income"`
}

// QuickAddParsed defines model for QuickAddParsed.
type QuickAddParsed struct {
	Amount      *float32            `json:"amount,omitempty"`
	Description *string             `json:"description,omitempty"`
	Type        *QuickAddParsedType `json:"type,omitempty"`
}

// QuickAddParsedType defines model for QuickAddParsed.Type.
type QuickAddParsedType string

// Transaction defines model for Transaction.
type Transaction struct {
	Amount          float32             `json:"amount"`
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	Currency        string              `json:"currency"`
	Date            openapi_types.Date  `json:"date"`
	Description     *string             `json:"description,omitempty"`
	GroupId         *openapi_types.UUID `json:"group_id,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	RecurringRuleId *openapi_types.UUID `json:"recurring_rule_id,omitempty"`
	Type            TransactionType     `json:"type"`
	UserId          openapi_types.UUID  `json:"user_id"`
}

// TransactionType defines model for Transaction.Type.
type TransactionType string

// TransactionCreate defines model for TransactionCreate.
type TransactionCreate struct {
	Amount      float32               `json:"amount"`
	Currency    string                `json:"currency"`
	Date        openapi_types.Date    `json:"date"`
	Description *string               `json:"description,omitempty"`
	GroupId     *openapi_types.UUID   `json:"group_id,omitempty"`
	Type        TransactionCreateType `json:"type"`
}

// TransactionCreateType defines model for TransactionCreate.Type.
type TransactionCreateType string

// TransactionList defines model for TransactionList.
type TransactionList struct {
	Data []Transaction `json:"data"`

	// NextCursor Cursor for the next page of results. Null if no more pages.
	NextCursor *string `json:"next_cursor"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetMonthlyReportParams defines parameters for GetMonthlyReport.
type GetMonthlyReportParams struct {
	Year    int                 `form:"year" json:"year"`
	Month   int                 `form:"month" json:"month"`
	GroupId *openapi_types.UUID `form:"group_id,omitempty" json:"group_id,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// GroupId Filter by family group
	GroupId *openapi_types.UUID `form:"group_id,omitempty" json:"group_id,omitempty"`

	// Cursor Cursor for pagination (e.g., encoded date + id)
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// QuickAddTransactionJSONBody defines parameters for QuickAddTransaction.
type QuickAddTransactionJSONBody struct {
	// Text Syntactic string generated by speech to text voice API.
	Text string `json:"text"`
}

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = FamilyGroupCreate

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionCreate

// QuickAddTransactionJSONRequestBody defines body for QuickAddTransaction for application/json ContentType.
type QuickAddTransactionJSONRequestBody QuickAddTransactionJSONBody
